services:
  - type: web
    name: stock-news-bot
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: python main.py
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.7
      - key: TELEGRAM_BOT_TOKEN
        sync: false
      - key: EMAIL_SENDER
        sync: false
      - key: EMAIL_PASSWORD
        sync: false
      - key: EMAIL_RECIPIENT
        sync: false
      - key: VIETCAPITAL_EMAILS
        sync: false
    healthCheckPath: /ping 
